// shared/proto/pentecost.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0--rc2
// source: pentecost.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmotionClass int32

const (
	EmotionClass_TEACHING       EmotionClass = 0
	EmotionClass_EXHORTATION    EmotionClass = 1
	EmotionClass_PROPHETIC_FIRE EmotionClass = 2
	EmotionClass_CELEBRATION    EmotionClass = 3
	EmotionClass_LAMENT         EmotionClass = 4
)

// Enum value maps for EmotionClass.
var (
	EmotionClass_name = map[int32]string{
		0: "TEACHING",
		1: "EXHORTATION",
		2: "PROPHETIC_FIRE",
		3: "CELEBRATION",
		4: "LAMENT",
	}
	EmotionClass_value = map[string]int32{
		"TEACHING":       0,
		"EXHORTATION":    1,
		"PROPHETIC_FIRE": 2,
		"CELEBRATION":    3,
		"LAMENT":         4,
	}
)

func (x EmotionClass) Enum() *EmotionClass {
	p := new(EmotionClass)
	*p = x
	return p
}

func (x EmotionClass) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EmotionClass) Descriptor() protoreflect.EnumDescriptor {
	return file_pentecost_proto_enumTypes[0].Descriptor()
}

func (EmotionClass) Type() protoreflect.EnumType {
	return &file_pentecost_proto_enumTypes[0]
}

func (x EmotionClass) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EmotionClass.Descriptor instead.
func (EmotionClass) EnumDescriptor() ([]byte, []int) {
	return file_pentecost_proto_rawDescGZIP(), []int{0}
}

// Layer 0: Ingestion
type AudioFrame struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PcmData        []byte                 `protobuf:"bytes,1,opt,name=pcm_data,json=pcmData,proto3" json:"pcm_data,omitempty"`
	SampleRate     int32                  `protobuf:"varint,2,opt,name=sample_rate,json=sampleRate,proto3" json:"sample_rate,omitempty"`
	Pts            int64                  `protobuf:"varint,3,opt,name=pts,proto3" json:"pts,omitempty"` // Presentation timestamp (microseconds)
	Dts            int64                  `protobuf:"varint,4,opt,name=dts,proto3" json:"dts,omitempty"` // Decode timestamp
	CapturedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=captured_at,json=capturedAt,proto3" json:"captured_at,omitempty"`
	SourceStreamId string                 `protobuf:"bytes,6,opt,name=source_stream_id,json=sourceStreamId,proto3" json:"source_stream_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AudioFrame) Reset() {
	*x = AudioFrame{}
	mi := &file_pentecost_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioFrame) ProtoMessage() {}

func (x *AudioFrame) ProtoReflect() protoreflect.Message {
	mi := &file_pentecost_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioFrame.ProtoReflect.Descriptor instead.
func (*AudioFrame) Descriptor() ([]byte, []int) {
	return file_pentecost_proto_rawDescGZIP(), []int{0}
}

func (x *AudioFrame) GetPcmData() []byte {
	if x != nil {
		return x.PcmData
	}
	return nil
}

func (x *AudioFrame) GetSampleRate() int32 {
	if x != nil {
		return x.SampleRate
	}
	return 0
}

func (x *AudioFrame) GetPts() int64 {
	if x != nil {
		return x.Pts
	}
	return 0
}

func (x *AudioFrame) GetDts() int64 {
	if x != nil {
		return x.Dts
	}
	return 0
}

func (x *AudioFrame) GetCapturedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CapturedAt
	}
	return nil
}

func (x *AudioFrame) GetSourceStreamId() string {
	if x != nil {
		return x.SourceStreamId
	}
	return ""
}

type VideoFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EncodedData   []byte                 `protobuf:"bytes,1,opt,name=encoded_data,json=encodedData,proto3" json:"encoded_data,omitempty"` // H.264 annex-b
	Width         int32                  `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	IsKeyframe    bool                   `protobuf:"varint,4,opt,name=is_keyframe,json=isKeyframe,proto3" json:"is_keyframe,omitempty"`
	Pts           int64                  `protobuf:"varint,5,opt,name=pts,proto3" json:"pts,omitempty"`
	Dts           int64                  `protobuf:"varint,6,opt,name=dts,proto3" json:"dts,omitempty"`
	CapturedAt    *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=captured_at,json=capturedAt,proto3" json:"captured_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoFrame) Reset() {
	*x = VideoFrame{}
	mi := &file_pentecost_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoFrame) ProtoMessage() {}

func (x *VideoFrame) ProtoReflect() protoreflect.Message {
	mi := &file_pentecost_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoFrame.ProtoReflect.Descriptor instead.
func (*VideoFrame) Descriptor() ([]byte, []int) {
	return file_pentecost_proto_rawDescGZIP(), []int{1}
}

func (x *VideoFrame) GetEncodedData() []byte {
	if x != nil {
		return x.EncodedData
	}
	return nil
}

func (x *VideoFrame) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *VideoFrame) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *VideoFrame) GetIsKeyframe() bool {
	if x != nil {
		return x.IsKeyframe
	}
	return false
}

func (x *VideoFrame) GetPts() int64 {
	if x != nil {
		return x.Pts
	}
	return 0
}

func (x *VideoFrame) GetDts() int64 {
	if x != nil {
		return x.Dts
	}
	return 0
}

func (x *VideoFrame) GetCapturedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CapturedAt
	}
	return nil
}

// Layer 1: ASR & Theology
type TranscriptionSegment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Confidence    float32                `protobuf:"fixed32,2,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Duration      *durationpb.Duration   `protobuf:"bytes,3,opt,name=duration,proto3" json:"duration,omitempty"`
	StartPts      int64                  `protobuf:"varint,4,opt,name=start_pts,json=startPts,proto3" json:"start_pts,omitempty"`
	EndPts        int64                  `protobuf:"varint,5,opt,name=end_pts,json=endPts,proto3" json:"end_pts,omitempty"`
	DetectedTerms []*TheologicalTerm     `protobuf:"bytes,6,rep,name=detected_terms,json=detectedTerms,proto3" json:"detected_terms,omitempty"`
	SpeakerId     string                 `protobuf:"bytes,7,opt,name=speaker_id,json=speakerId,proto3" json:"speaker_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranscriptionSegment) Reset() {
	*x = TranscriptionSegment{}
	mi := &file_pentecost_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranscriptionSegment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranscriptionSegment) ProtoMessage() {}

func (x *TranscriptionSegment) ProtoReflect() protoreflect.Message {
	mi := &file_pentecost_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranscriptionSegment.ProtoReflect.Descriptor instead.
func (*TranscriptionSegment) Descriptor() ([]byte, []int) {
	return file_pentecost_proto_rawDescGZIP(), []int{2}
}

func (x *TranscriptionSegment) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *TranscriptionSegment) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *TranscriptionSegment) GetDuration() *durationpb.Duration {
	if x != nil {
		return x.Duration
	}
	return nil
}

func (x *TranscriptionSegment) GetStartPts() int64 {
	if x != nil {
		return x.StartPts
	}
	return 0
}

func (x *TranscriptionSegment) GetEndPts() int64 {
	if x != nil {
		return x.EndPts
	}
	return 0
}

func (x *TranscriptionSegment) GetDetectedTerms() []*TheologicalTerm {
	if x != nil {
		return x.DetectedTerms
	}
	return nil
}

func (x *TranscriptionSegment) GetSpeakerId() string {
	if x != nil {
		return x.SpeakerId
	}
	return ""
}

type TheologicalTerm struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Term             string                 `protobuf:"bytes,1,opt,name=term,proto3" json:"term,omitempty"`
	OriginalLanguage string                 `protobuf:"bytes,2,opt,name=original_language,json=originalLanguage,proto3" json:"original_language,omitempty"` // "greek", "hebrew", "english"
	Transliteration  string                 `protobuf:"bytes,3,opt,name=transliteration,proto3" json:"transliteration,omitempty"`
	DoctrinalWeight  float32                `protobuf:"fixed32,4,opt,name=doctrinal_weight,json=doctrinalWeight,proto3" json:"doctrinal_weight,omitempty"` // 0.0-1.0 importance
	DoctrinalContext []string               `protobuf:"bytes,5,rep,name=doctrinal_context,json=doctrinalContext,proto3" json:"doctrinal_context,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TheologicalTerm) Reset() {
	*x = TheologicalTerm{}
	mi := &file_pentecost_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TheologicalTerm) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TheologicalTerm) ProtoMessage() {}

func (x *TheologicalTerm) ProtoReflect() protoreflect.Message {
	mi := &file_pentecost_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TheologicalTerm.ProtoReflect.Descriptor instead.
func (*TheologicalTerm) Descriptor() ([]byte, []int) {
	return file_pentecost_proto_rawDescGZIP(), []int{3}
}

func (x *TheologicalTerm) GetTerm() string {
	if x != nil {
		return x.Term
	}
	return ""
}

func (x *TheologicalTerm) GetOriginalLanguage() string {
	if x != nil {
		return x.OriginalLanguage
	}
	return ""
}

func (x *TheologicalTerm) GetTransliteration() string {
	if x != nil {
		return x.Transliteration
	}
	return ""
}

func (x *TheologicalTerm) GetDoctrinalWeight() float32 {
	if x != nil {
		return x.DoctrinalWeight
	}
	return 0
}

func (x *TheologicalTerm) GetDoctrinalContext() []string {
	if x != nil {
		return x.DoctrinalContext
	}
	return nil
}

type VerifiedTranslation struct {
	state                protoimpl.MessageState   `protogen:"open.v1"`
	OriginalText         string                   `protobuf:"bytes,1,opt,name=original_text,json=originalText,proto3" json:"original_text,omitempty"`
	TranslatedText       string                   `protobuf:"bytes,2,opt,name=translated_text,json=translatedText,proto3" json:"translated_text,omitempty"`
	TargetLanguage       string                   `protobuf:"bytes,3,opt,name=target_language,json=targetLanguage,proto3" json:"target_language,omitempty"` // ISO 639-1
	DoctrinalSafetyScore float32                  `protobuf:"fixed32,4,opt,name=doctrinal_safety_score,json=doctrinalSafetyScore,proto3" json:"doctrinal_safety_score,omitempty"`
	Corrections          []*TranslationCorrection `protobuf:"bytes,5,rep,name=corrections,proto3" json:"corrections,omitempty"`
	ProcessingLatencyMs  int64                    `protobuf:"varint,6,opt,name=processing_latency_ms,json=processingLatencyMs,proto3" json:"processing_latency_ms,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *VerifiedTranslation) Reset() {
	*x = VerifiedTranslation{}
	mi := &file_pentecost_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifiedTranslation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifiedTranslation) ProtoMessage() {}

func (x *VerifiedTranslation) ProtoReflect() protoreflect.Message {
	mi := &file_pentecost_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifiedTranslation.ProtoReflect.Descriptor instead.
func (*VerifiedTranslation) Descriptor() ([]byte, []int) {
	return file_pentecost_proto_rawDescGZIP(), []int{4}
}

func (x *VerifiedTranslation) GetOriginalText() string {
	if x != nil {
		return x.OriginalText
	}
	return ""
}

func (x *VerifiedTranslation) GetTranslatedText() string {
	if x != nil {
		return x.TranslatedText
	}
	return ""
}

func (x *VerifiedTranslation) GetTargetLanguage() string {
	if x != nil {
		return x.TargetLanguage
	}
	return ""
}

func (x *VerifiedTranslation) GetDoctrinalSafetyScore() float32 {
	if x != nil {
		return x.DoctrinalSafetyScore
	}
	return 0
}

func (x *VerifiedTranslation) GetCorrections() []*TranslationCorrection {
	if x != nil {
		return x.Corrections
	}
	return nil
}

func (x *VerifiedTranslation) GetProcessingLatencyMs() int64 {
	if x != nil {
		return x.ProcessingLatencyMs
	}
	return 0
}

type TranslationCorrection struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Term                 string                 `protobuf:"bytes,1,opt,name=term,proto3" json:"term,omitempty"`
	IncorrectTranslation string                 `protobuf:"bytes,2,opt,name=incorrect_translation,json=incorrectTranslation,proto3" json:"incorrect_translation,omitempty"`
	CorrectTranslation   string                 `protobuf:"bytes,3,opt,name=correct_translation,json=correctTranslation,proto3" json:"correct_translation,omitempty"`
	DoctrinalReasoning   string                 `protobuf:"bytes,4,opt,name=doctrinal_reasoning,json=doctrinalReasoning,proto3" json:"doctrinal_reasoning,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *TranslationCorrection) Reset() {
	*x = TranslationCorrection{}
	mi := &file_pentecost_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranslationCorrection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranslationCorrection) ProtoMessage() {}

func (x *TranslationCorrection) ProtoReflect() protoreflect.Message {
	mi := &file_pentecost_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranslationCorrection.ProtoReflect.Descriptor instead.
func (*TranslationCorrection) Descriptor() ([]byte, []int) {
	return file_pentecost_proto_rawDescGZIP(), []int{5}
}

func (x *TranslationCorrection) GetTerm() string {
	if x != nil {
		return x.Term
	}
	return ""
}

func (x *TranslationCorrection) GetIncorrectTranslation() string {
	if x != nil {
		return x.IncorrectTranslation
	}
	return ""
}

func (x *TranslationCorrection) GetCorrectTranslation() string {
	if x != nil {
		return x.CorrectTranslation
	}
	return ""
}

func (x *TranslationCorrection) GetDoctrinalReasoning() string {
	if x != nil {
		return x.DoctrinalReasoning
	}
	return ""
}

// Layer 2: TTS
type SynthesisRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Text           string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	TargetLanguage string                 `protobuf:"bytes,3,opt,name=target_language,json=targetLanguage,proto3" json:"target_language,omitempty"`
	Emotion        *EmotionalContext      `protobuf:"bytes,4,opt,name=emotion,proto3" json:"emotion,omitempty"`
	ReferenceAudio []byte                 `protobuf:"bytes,5,opt,name=reference_audio,json=referenceAudio,proto3" json:"reference_audio,omitempty"` // 10s rolling window
	ReferencePts   int64                  `protobuf:"varint,6,opt,name=reference_pts,json=referencePts,proto3" json:"reference_pts,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SynthesisRequest) Reset() {
	*x = SynthesisRequest{}
	mi := &file_pentecost_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SynthesisRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SynthesisRequest) ProtoMessage() {}

func (x *SynthesisRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pentecost_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SynthesisRequest.ProtoReflect.Descriptor instead.
func (*SynthesisRequest) Descriptor() ([]byte, []int) {
	return file_pentecost_proto_rawDescGZIP(), []int{6}
}

func (x *SynthesisRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *SynthesisRequest) GetTargetLanguage() string {
	if x != nil {
		return x.TargetLanguage
	}
	return ""
}

func (x *SynthesisRequest) GetEmotion() *EmotionalContext {
	if x != nil {
		return x.Emotion
	}
	return nil
}

func (x *SynthesisRequest) GetReferenceAudio() []byte {
	if x != nil {
		return x.ReferenceAudio
	}
	return nil
}

func (x *SynthesisRequest) GetReferencePts() int64 {
	if x != nil {
		return x.ReferencePts
	}
	return 0
}

type EmotionalContext struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	PitchMean         float32                `protobuf:"fixed32,1,opt,name=pitch_mean,json=pitchMean,proto3" json:"pitch_mean,omitempty"`
	PitchStd          float32                `protobuf:"fixed32,2,opt,name=pitch_std,json=pitchStd,proto3" json:"pitch_std,omitempty"`
	EnergyMean        float32                `protobuf:"fixed32,3,opt,name=energy_mean,json=energyMean,proto3" json:"energy_mean,omitempty"`
	EnergyStd         float32                `protobuf:"fixed32,4,opt,name=energy_std,json=energyStd,proto3" json:"energy_std,omitempty"`
	SpeakingRate      float32                `protobuf:"fixed32,5,opt,name=speaking_rate,json=speakingRate,proto3" json:"speaking_rate,omitempty"` // words per minute
	ClassifiedEmotion EmotionClass           `protobuf:"varint,6,opt,name=classified_emotion,json=classifiedEmotion,proto3,enum=pentecost.EmotionClass" json:"classified_emotion,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *EmotionalContext) Reset() {
	*x = EmotionalContext{}
	mi := &file_pentecost_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmotionalContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmotionalContext) ProtoMessage() {}

func (x *EmotionalContext) ProtoReflect() protoreflect.Message {
	mi := &file_pentecost_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmotionalContext.ProtoReflect.Descriptor instead.
func (*EmotionalContext) Descriptor() ([]byte, []int) {
	return file_pentecost_proto_rawDescGZIP(), []int{7}
}

func (x *EmotionalContext) GetPitchMean() float32 {
	if x != nil {
		return x.PitchMean
	}
	return 0
}

func (x *EmotionalContext) GetPitchStd() float32 {
	if x != nil {
		return x.PitchStd
	}
	return 0
}

func (x *EmotionalContext) GetEnergyMean() float32 {
	if x != nil {
		return x.EnergyMean
	}
	return 0
}

func (x *EmotionalContext) GetEnergyStd() float32 {
	if x != nil {
		return x.EnergyStd
	}
	return 0
}

func (x *EmotionalContext) GetSpeakingRate() float32 {
	if x != nil {
		return x.SpeakingRate
	}
	return 0
}

func (x *EmotionalContext) GetClassifiedEmotion() EmotionClass {
	if x != nil {
		return x.ClassifiedEmotion
	}
	return EmotionClass_TEACHING
}

type SynthesizedAudio struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	PcmData               []byte                 `protobuf:"bytes,1,opt,name=pcm_data,json=pcmData,proto3" json:"pcm_data,omitempty"`
	SampleRate            int32                  `protobuf:"varint,2,opt,name=sample_rate,json=sampleRate,proto3" json:"sample_rate,omitempty"`
	Pts                   int64                  `protobuf:"varint,3,opt,name=pts,proto3" json:"pts,omitempty"`
	Duration              *durationpb.Duration   `protobuf:"bytes,4,opt,name=duration,proto3" json:"duration,omitempty"`
	AppliedEmotion        *EmotionalContext      `protobuf:"bytes,5,opt,name=applied_emotion,json=appliedEmotion,proto3" json:"applied_emotion,omitempty"`
	SimilarityToReference float32                `protobuf:"fixed32,6,opt,name=similarity_to_reference,json=similarityToReference,proto3" json:"similarity_to_reference,omitempty"` // Voice cloning quality
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *SynthesizedAudio) Reset() {
	*x = SynthesizedAudio{}
	mi := &file_pentecost_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SynthesizedAudio) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SynthesizedAudio) ProtoMessage() {}

func (x *SynthesizedAudio) ProtoReflect() protoreflect.Message {
	mi := &file_pentecost_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SynthesizedAudio.ProtoReflect.Descriptor instead.
func (*SynthesizedAudio) Descriptor() ([]byte, []int) {
	return file_pentecost_proto_rawDescGZIP(), []int{8}
}

func (x *SynthesizedAudio) GetPcmData() []byte {
	if x != nil {
		return x.PcmData
	}
	return nil
}

func (x *SynthesizedAudio) GetSampleRate() int32 {
	if x != nil {
		return x.SampleRate
	}
	return 0
}

func (x *SynthesizedAudio) GetPts() int64 {
	if x != nil {
		return x.Pts
	}
	return 0
}

func (x *SynthesizedAudio) GetDuration() *durationpb.Duration {
	if x != nil {
		return x.Duration
	}
	return nil
}

func (x *SynthesizedAudio) GetAppliedEmotion() *EmotionalContext {
	if x != nil {
		return x.AppliedEmotion
	}
	return nil
}

func (x *SynthesizedAudio) GetSimilarityToReference() float32 {
	if x != nil {
		return x.SimilarityToReference
	}
	return 0
}

// Layer 3: Video Sync
type VideoSyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoFrames   [][]byte               `protobuf:"bytes,1,rep,name=video_frames,json=videoFrames,proto3" json:"video_frames,omitempty"`       // Encoded frames
	AudioFeatures []byte                 `protobuf:"bytes,2,opt,name=audio_features,json=audioFeatures,proto3" json:"audio_features,omitempty"` // Whisper embeddings
	Prosody       *ProsodyData           `protobuf:"bytes,3,opt,name=prosody,proto3" json:"prosody,omitempty"`
	SegmentId     int64                  `protobuf:"varint,4,opt,name=segment_id,json=segmentId,proto3" json:"segment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoSyncRequest) Reset() {
	*x = VideoSyncRequest{}
	mi := &file_pentecost_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoSyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoSyncRequest) ProtoMessage() {}

func (x *VideoSyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pentecost_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoSyncRequest.ProtoReflect.Descriptor instead.
func (*VideoSyncRequest) Descriptor() ([]byte, []int) {
	return file_pentecost_proto_rawDescGZIP(), []int{9}
}

func (x *VideoSyncRequest) GetVideoFrames() [][]byte {
	if x != nil {
		return x.VideoFrames
	}
	return nil
}

func (x *VideoSyncRequest) GetAudioFeatures() []byte {
	if x != nil {
		return x.AudioFeatures
	}
	return nil
}

func (x *VideoSyncRequest) GetProsody() *ProsodyData {
	if x != nil {
		return x.Prosody
	}
	return nil
}

func (x *VideoSyncRequest) GetSegmentId() int64 {
	if x != nil {
		return x.SegmentId
	}
	return 0
}

type ProsodyData struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PitchContour   []float32              `protobuf:"fixed32,1,rep,packed,name=pitch_contour,json=pitchContour,proto3" json:"pitch_contour,omitempty"`
	EnergyEnvelope []float32              `protobuf:"fixed32,2,rep,packed,name=energy_envelope,json=energyEnvelope,proto3" json:"energy_envelope,omitempty"`
	EnergyPeaks    []int32                `protobuf:"varint,3,rep,packed,name=energy_peaks,json=energyPeaks,proto3" json:"energy_peaks,omitempty"` // Frame indices of emphasis
	Tempo          float32                `protobuf:"fixed32,4,opt,name=tempo,proto3" json:"tempo,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProsodyData) Reset() {
	*x = ProsodyData{}
	mi := &file_pentecost_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProsodyData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProsodyData) ProtoMessage() {}

func (x *ProsodyData) ProtoReflect() protoreflect.Message {
	mi := &file_pentecost_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProsodyData.ProtoReflect.Descriptor instead.
func (*ProsodyData) Descriptor() ([]byte, []int) {
	return file_pentecost_proto_rawDescGZIP(), []int{10}
}

func (x *ProsodyData) GetPitchContour() []float32 {
	if x != nil {
		return x.PitchContour
	}
	return nil
}

func (x *ProsodyData) GetEnergyEnvelope() []float32 {
	if x != nil {
		return x.EnergyEnvelope
	}
	return nil
}

func (x *ProsodyData) GetEnergyPeaks() []int32 {
	if x != nil {
		return x.EnergyPeaks
	}
	return nil
}

func (x *ProsodyData) GetTempo() float32 {
	if x != nil {
		return x.Tempo
	}
	return 0
}

type SynchronizedVideo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SyncedFrames     [][]byte               `protobuf:"bytes,1,rep,name=synced_frames,json=syncedFrames,proto3" json:"synced_frames,omitempty"`
	SegmentId        int64                  `protobuf:"varint,2,opt,name=segment_id,json=segmentId,proto3" json:"segment_id,omitempty"`
	SyncQualityScore float32                `protobuf:"fixed32,3,opt,name=sync_quality_score,json=syncQualityScore,proto3" json:"sync_quality_score,omitempty"` // Lip-sync accuracy
	ProcessingTime   *durationpb.Duration   `protobuf:"bytes,4,opt,name=processing_time,json=processingTime,proto3" json:"processing_time,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SynchronizedVideo) Reset() {
	*x = SynchronizedVideo{}
	mi := &file_pentecost_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SynchronizedVideo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SynchronizedVideo) ProtoMessage() {}

func (x *SynchronizedVideo) ProtoReflect() protoreflect.Message {
	mi := &file_pentecost_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SynchronizedVideo.ProtoReflect.Descriptor instead.
func (*SynchronizedVideo) Descriptor() ([]byte, []int) {
	return file_pentecost_proto_rawDescGZIP(), []int{11}
}

func (x *SynchronizedVideo) GetSyncedFrames() [][]byte {
	if x != nil {
		return x.SyncedFrames
	}
	return nil
}

func (x *SynchronizedVideo) GetSegmentId() int64 {
	if x != nil {
		return x.SegmentId
	}
	return 0
}

func (x *SynchronizedVideo) GetSyncQualityScore() float32 {
	if x != nil {
		return x.SyncQualityScore
	}
	return 0
}

func (x *SynchronizedVideo) GetProcessingTime() *durationpb.Duration {
	if x != nil {
		return x.ProcessingTime
	}
	return nil
}

// Layer 4: Broadcast
type BroadcastSegment struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Media:
	//
	//	*BroadcastSegment_Video
	//	*BroadcastSegment_Audio
	Media         isBroadcastSegment_Media `protobuf_oneof:"media"`
	Dialect       string                   `protobuf:"bytes,3,opt,name=dialect,proto3" json:"dialect,omitempty"`
	SegmentId     int64                    `protobuf:"varint,4,opt,name=segment_id,json=segmentId,proto3" json:"segment_id,omitempty"`
	Pts           int64                    `protobuf:"varint,5,opt,name=pts,proto3" json:"pts,omitempty"`
	IsKeyframe    bool                     `protobuf:"varint,6,opt,name=is_keyframe,json=isKeyframe,proto3" json:"is_keyframe,omitempty"`
	BroadcastAt   *timestamppb.Timestamp   `protobuf:"bytes,7,opt,name=broadcast_at,json=broadcastAt,proto3" json:"broadcast_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BroadcastSegment) Reset() {
	*x = BroadcastSegment{}
	mi := &file_pentecost_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BroadcastSegment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastSegment) ProtoMessage() {}

func (x *BroadcastSegment) ProtoReflect() protoreflect.Message {
	mi := &file_pentecost_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastSegment.ProtoReflect.Descriptor instead.
func (*BroadcastSegment) Descriptor() ([]byte, []int) {
	return file_pentecost_proto_rawDescGZIP(), []int{12}
}

func (x *BroadcastSegment) GetMedia() isBroadcastSegment_Media {
	if x != nil {
		return x.Media
	}
	return nil
}

func (x *BroadcastSegment) GetVideo() *SynchronizedVideo {
	if x != nil {
		if x, ok := x.Media.(*BroadcastSegment_Video); ok {
			return x.Video
		}
	}
	return nil
}

func (x *BroadcastSegment) GetAudio() *SynthesizedAudio {
	if x != nil {
		if x, ok := x.Media.(*BroadcastSegment_Audio); ok {
			return x.Audio
		}
	}
	return nil
}

func (x *BroadcastSegment) GetDialect() string {
	if x != nil {
		return x.Dialect
	}
	return ""
}

func (x *BroadcastSegment) GetSegmentId() int64 {
	if x != nil {
		return x.SegmentId
	}
	return 0
}

func (x *BroadcastSegment) GetPts() int64 {
	if x != nil {
		return x.Pts
	}
	return 0
}

func (x *BroadcastSegment) GetIsKeyframe() bool {
	if x != nil {
		return x.IsKeyframe
	}
	return false
}

func (x *BroadcastSegment) GetBroadcastAt() *timestamppb.Timestamp {
	if x != nil {
		return x.BroadcastAt
	}
	return nil
}

type isBroadcastSegment_Media interface {
	isBroadcastSegment_Media()
}

type BroadcastSegment_Video struct {
	Video *SynchronizedVideo `protobuf:"bytes,1,opt,name=video,proto3,oneof"`
}

type BroadcastSegment_Audio struct {
	Audio *SynthesizedAudio `protobuf:"bytes,2,opt,name=audio,proto3,oneof"`
}

func (*BroadcastSegment_Video) isBroadcastSegment_Media() {}

func (*BroadcastSegment_Audio) isBroadcastSegment_Media() {}

// Metrics & Monitoring
type PerformanceMetrics struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ServiceName        string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Timestamp          *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	LatencyHistogram   map[string]float32     `protobuf:"bytes,3,rep,name=latency_histogram,json=latencyHistogram,proto3" json:"latency_histogram,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed32,2,opt,name=value"`
	ThroughputCounters map[string]int64       `protobuf:"bytes,4,rep,name=throughput_counters,json=throughputCounters,proto3" json:"throughput_counters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	ErrorSamples       []string               `protobuf:"bytes,5,rep,name=error_samples,json=errorSamples,proto3" json:"error_samples,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PerformanceMetrics) Reset() {
	*x = PerformanceMetrics{}
	mi := &file_pentecost_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PerformanceMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PerformanceMetrics) ProtoMessage() {}

func (x *PerformanceMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_pentecost_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PerformanceMetrics.ProtoReflect.Descriptor instead.
func (*PerformanceMetrics) Descriptor() ([]byte, []int) {
	return file_pentecost_proto_rawDescGZIP(), []int{13}
}

func (x *PerformanceMetrics) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *PerformanceMetrics) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *PerformanceMetrics) GetLatencyHistogram() map[string]float32 {
	if x != nil {
		return x.LatencyHistogram
	}
	return nil
}

func (x *PerformanceMetrics) GetThroughputCounters() map[string]int64 {
	if x != nil {
		return x.ThroughputCounters
	}
	return nil
}

func (x *PerformanceMetrics) GetErrorSamples() []string {
	if x != nil {
		return x.ErrorSamples
	}
	return nil
}

var File_pentecost_proto protoreflect.FileDescriptor

const file_pentecost_proto_rawDesc = "" +
	"\n" +
	"\x0fpentecost.proto\x12\tpentecost\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\"\xd3\x01\n" +
	"\n" +
	"AudioFrame\x12\x19\n" +
	"\bpcm_data\x18\x01 \x01(\fR\apcmData\x12\x1f\n" +
	"\vsample_rate\x18\x02 \x01(\x05R\n" +
	"sampleRate\x12\x10\n" +
	"\x03pts\x18\x03 \x01(\x03R\x03pts\x12\x10\n" +
	"\x03dts\x18\x04 \x01(\x03R\x03dts\x12;\n" +
	"\vcaptured_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"capturedAt\x12(\n" +
	"\x10source_stream_id\x18\x06 \x01(\tR\x0esourceStreamId\"\xdf\x01\n" +
	"\n" +
	"VideoFrame\x12!\n" +
	"\fencoded_data\x18\x01 \x01(\fR\vencodedData\x12\x14\n" +
	"\x05width\x18\x02 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x03 \x01(\x05R\x06height\x12\x1f\n" +
	"\vis_keyframe\x18\x04 \x01(\bR\n" +
	"isKeyframe\x12\x10\n" +
	"\x03pts\x18\x05 \x01(\x03R\x03pts\x12\x10\n" +
	"\x03dts\x18\x06 \x01(\x03R\x03dts\x12;\n" +
	"\vcaptured_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"capturedAt\"\x99\x02\n" +
	"\x14TranscriptionSegment\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x1e\n" +
	"\n" +
	"confidence\x18\x02 \x01(\x02R\n" +
	"confidence\x125\n" +
	"\bduration\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\bduration\x12\x1b\n" +
	"\tstart_pts\x18\x04 \x01(\x03R\bstartPts\x12\x17\n" +
	"\aend_pts\x18\x05 \x01(\x03R\x06endPts\x12A\n" +
	"\x0edetected_terms\x18\x06 \x03(\v2\x1a.pentecost.TheologicalTermR\rdetectedTerms\x12\x1d\n" +
	"\n" +
	"speaker_id\x18\a \x01(\tR\tspeakerId\"\xd4\x01\n" +
	"\x0fTheologicalTerm\x12\x12\n" +
	"\x04term\x18\x01 \x01(\tR\x04term\x12+\n" +
	"\x11original_language\x18\x02 \x01(\tR\x10originalLanguage\x12(\n" +
	"\x0ftransliteration\x18\x03 \x01(\tR\x0ftransliteration\x12)\n" +
	"\x10doctrinal_weight\x18\x04 \x01(\x02R\x0fdoctrinalWeight\x12+\n" +
	"\x11doctrinal_context\x18\x05 \x03(\tR\x10doctrinalContext\"\xba\x02\n" +
	"\x13VerifiedTranslation\x12#\n" +
	"\roriginal_text\x18\x01 \x01(\tR\foriginalText\x12'\n" +
	"\x0ftranslated_text\x18\x02 \x01(\tR\x0etranslatedText\x12'\n" +
	"\x0ftarget_language\x18\x03 \x01(\tR\x0etargetLanguage\x124\n" +
	"\x16doctrinal_safety_score\x18\x04 \x01(\x02R\x14doctrinalSafetyScore\x12B\n" +
	"\vcorrections\x18\x05 \x03(\v2 .pentecost.TranslationCorrectionR\vcorrections\x122\n" +
	"\x15processing_latency_ms\x18\x06 \x01(\x03R\x13processingLatencyMs\"\xc2\x01\n" +
	"\x15TranslationCorrection\x12\x12\n" +
	"\x04term\x18\x01 \x01(\tR\x04term\x123\n" +
	"\x15incorrect_translation\x18\x02 \x01(\tR\x14incorrectTranslation\x12/\n" +
	"\x13correct_translation\x18\x03 \x01(\tR\x12correctTranslation\x12/\n" +
	"\x13doctrinal_reasoning\x18\x04 \x01(\tR\x12doctrinalReasoning\"\xd4\x01\n" +
	"\x10SynthesisRequest\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12'\n" +
	"\x0ftarget_language\x18\x03 \x01(\tR\x0etargetLanguage\x125\n" +
	"\aemotion\x18\x04 \x01(\v2\x1b.pentecost.EmotionalContextR\aemotion\x12'\n" +
	"\x0freference_audio\x18\x05 \x01(\fR\x0ereferenceAudio\x12#\n" +
	"\rreference_pts\x18\x06 \x01(\x03R\freferencePts\"\xfb\x01\n" +
	"\x10EmotionalContext\x12\x1d\n" +
	"\n" +
	"pitch_mean\x18\x01 \x01(\x02R\tpitchMean\x12\x1b\n" +
	"\tpitch_std\x18\x02 \x01(\x02R\bpitchStd\x12\x1f\n" +
	"\venergy_mean\x18\x03 \x01(\x02R\n" +
	"energyMean\x12\x1d\n" +
	"\n" +
	"energy_std\x18\x04 \x01(\x02R\tenergyStd\x12#\n" +
	"\rspeaking_rate\x18\x05 \x01(\x02R\fspeakingRate\x12F\n" +
	"\x12classified_emotion\x18\x06 \x01(\x0e2\x17.pentecost.EmotionClassR\x11classifiedEmotion\"\x95\x02\n" +
	"\x10SynthesizedAudio\x12\x19\n" +
	"\bpcm_data\x18\x01 \x01(\fR\apcmData\x12\x1f\n" +
	"\vsample_rate\x18\x02 \x01(\x05R\n" +
	"sampleRate\x12\x10\n" +
	"\x03pts\x18\x03 \x01(\x03R\x03pts\x125\n" +
	"\bduration\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\bduration\x12D\n" +
	"\x0fapplied_emotion\x18\x05 \x01(\v2\x1b.pentecost.EmotionalContextR\x0eappliedEmotion\x126\n" +
	"\x17similarity_to_reference\x18\x06 \x01(\x02R\x15similarityToReference\"\xad\x01\n" +
	"\x10VideoSyncRequest\x12!\n" +
	"\fvideo_frames\x18\x01 \x03(\fR\vvideoFrames\x12%\n" +
	"\x0eaudio_features\x18\x02 \x01(\fR\raudioFeatures\x120\n" +
	"\aprosody\x18\x03 \x01(\v2\x16.pentecost.ProsodyDataR\aprosody\x12\x1d\n" +
	"\n" +
	"segment_id\x18\x04 \x01(\x03R\tsegmentId\"\x94\x01\n" +
	"\vProsodyData\x12#\n" +
	"\rpitch_contour\x18\x01 \x03(\x02R\fpitchContour\x12'\n" +
	"\x0fenergy_envelope\x18\x02 \x03(\x02R\x0eenergyEnvelope\x12!\n" +
	"\fenergy_peaks\x18\x03 \x03(\x05R\venergyPeaks\x12\x14\n" +
	"\x05tempo\x18\x04 \x01(\x02R\x05tempo\"\xc9\x01\n" +
	"\x11SynchronizedVideo\x12#\n" +
	"\rsynced_frames\x18\x01 \x03(\fR\fsyncedFrames\x12\x1d\n" +
	"\n" +
	"segment_id\x18\x02 \x01(\x03R\tsegmentId\x12,\n" +
	"\x12sync_quality_score\x18\x03 \x01(\x02R\x10syncQualityScore\x12B\n" +
	"\x0fprocessing_time\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\x0eprocessingTime\"\xb1\x02\n" +
	"\x10BroadcastSegment\x124\n" +
	"\x05video\x18\x01 \x01(\v2\x1c.pentecost.SynchronizedVideoH\x00R\x05video\x123\n" +
	"\x05audio\x18\x02 \x01(\v2\x1b.pentecost.SynthesizedAudioH\x00R\x05audio\x12\x18\n" +
	"\adialect\x18\x03 \x01(\tR\adialect\x12\x1d\n" +
	"\n" +
	"segment_id\x18\x04 \x01(\x03R\tsegmentId\x12\x10\n" +
	"\x03pts\x18\x05 \x01(\x03R\x03pts\x12\x1f\n" +
	"\vis_keyframe\x18\x06 \x01(\bR\n" +
	"isKeyframe\x12=\n" +
	"\fbroadcast_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\vbroadcastAtB\a\n" +
	"\x05media\"\xec\x03\n" +
	"\x12PerformanceMetrics\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12`\n" +
	"\x11latency_histogram\x18\x03 \x03(\v23.pentecost.PerformanceMetrics.LatencyHistogramEntryR\x10latencyHistogram\x12f\n" +
	"\x13throughput_counters\x18\x04 \x03(\v25.pentecost.PerformanceMetrics.ThroughputCountersEntryR\x12throughputCounters\x12#\n" +
	"\rerror_samples\x18\x05 \x03(\tR\ferrorSamples\x1aC\n" +
	"\x15LatencyHistogramEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x02R\x05value:\x028\x01\x1aE\n" +
	"\x17ThroughputCountersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01*^\n" +
	"\fEmotionClass\x12\f\n" +
	"\bTEACHING\x10\x00\x12\x0f\n" +
	"\vEXHORTATION\x10\x01\x12\x12\n" +
	"\x0ePROPHETIC_FIRE\x10\x02\x12\x0f\n" +
	"\vCELEBRATION\x10\x03\x12\n" +
	"\n" +
	"\x06LAMENT\x10\x04B8Z6github.com/RaymondAkachi/pentecost-engine/shared/typesb\x06proto3"

var (
	file_pentecost_proto_rawDescOnce sync.Once
	file_pentecost_proto_rawDescData []byte
)

func file_pentecost_proto_rawDescGZIP() []byte {
	file_pentecost_proto_rawDescOnce.Do(func() {
		file_pentecost_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pentecost_proto_rawDesc), len(file_pentecost_proto_rawDesc)))
	})
	return file_pentecost_proto_rawDescData
}

var file_pentecost_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pentecost_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_pentecost_proto_goTypes = []any{
	(EmotionClass)(0),             // 0: pentecost.EmotionClass
	(*AudioFrame)(nil),            // 1: pentecost.AudioFrame
	(*VideoFrame)(nil),            // 2: pentecost.VideoFrame
	(*TranscriptionSegment)(nil),  // 3: pentecost.TranscriptionSegment
	(*TheologicalTerm)(nil),       // 4: pentecost.TheologicalTerm
	(*VerifiedTranslation)(nil),   // 5: pentecost.VerifiedTranslation
	(*TranslationCorrection)(nil), // 6: pentecost.TranslationCorrection
	(*SynthesisRequest)(nil),      // 7: pentecost.SynthesisRequest
	(*EmotionalContext)(nil),      // 8: pentecost.EmotionalContext
	(*SynthesizedAudio)(nil),      // 9: pentecost.SynthesizedAudio
	(*VideoSyncRequest)(nil),      // 10: pentecost.VideoSyncRequest
	(*ProsodyData)(nil),           // 11: pentecost.ProsodyData
	(*SynchronizedVideo)(nil),     // 12: pentecost.SynchronizedVideo
	(*BroadcastSegment)(nil),      // 13: pentecost.BroadcastSegment
	(*PerformanceMetrics)(nil),    // 14: pentecost.PerformanceMetrics
	nil,                           // 15: pentecost.PerformanceMetrics.LatencyHistogramEntry
	nil,                           // 16: pentecost.PerformanceMetrics.ThroughputCountersEntry
	(*timestamppb.Timestamp)(nil), // 17: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),   // 18: google.protobuf.Duration
}
var file_pentecost_proto_depIdxs = []int32{
	17, // 0: pentecost.AudioFrame.captured_at:type_name -> google.protobuf.Timestamp
	17, // 1: pentecost.VideoFrame.captured_at:type_name -> google.protobuf.Timestamp
	18, // 2: pentecost.TranscriptionSegment.duration:type_name -> google.protobuf.Duration
	4,  // 3: pentecost.TranscriptionSegment.detected_terms:type_name -> pentecost.TheologicalTerm
	6,  // 4: pentecost.VerifiedTranslation.corrections:type_name -> pentecost.TranslationCorrection
	8,  // 5: pentecost.SynthesisRequest.emotion:type_name -> pentecost.EmotionalContext
	0,  // 6: pentecost.EmotionalContext.classified_emotion:type_name -> pentecost.EmotionClass
	18, // 7: pentecost.SynthesizedAudio.duration:type_name -> google.protobuf.Duration
	8,  // 8: pentecost.SynthesizedAudio.applied_emotion:type_name -> pentecost.EmotionalContext
	11, // 9: pentecost.VideoSyncRequest.prosody:type_name -> pentecost.ProsodyData
	18, // 10: pentecost.SynchronizedVideo.processing_time:type_name -> google.protobuf.Duration
	12, // 11: pentecost.BroadcastSegment.video:type_name -> pentecost.SynchronizedVideo
	9,  // 12: pentecost.BroadcastSegment.audio:type_name -> pentecost.SynthesizedAudio
	17, // 13: pentecost.BroadcastSegment.broadcast_at:type_name -> google.protobuf.Timestamp
	17, // 14: pentecost.PerformanceMetrics.timestamp:type_name -> google.protobuf.Timestamp
	15, // 15: pentecost.PerformanceMetrics.latency_histogram:type_name -> pentecost.PerformanceMetrics.LatencyHistogramEntry
	16, // 16: pentecost.PerformanceMetrics.throughput_counters:type_name -> pentecost.PerformanceMetrics.ThroughputCountersEntry
	17, // [17:17] is the sub-list for method output_type
	17, // [17:17] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_pentecost_proto_init() }
func file_pentecost_proto_init() {
	if File_pentecost_proto != nil {
		return
	}
	file_pentecost_proto_msgTypes[12].OneofWrappers = []any{
		(*BroadcastSegment_Video)(nil),
		(*BroadcastSegment_Audio)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pentecost_proto_rawDesc), len(file_pentecost_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pentecost_proto_goTypes,
		DependencyIndexes: file_pentecost_proto_depIdxs,
		EnumInfos:         file_pentecost_proto_enumTypes,
		MessageInfos:      file_pentecost_proto_msgTypes,
	}.Build()
	File_pentecost_proto = out.File
	file_pentecost_proto_goTypes = nil
	file_pentecost_proto_depIdxs = nil
}
